crowdED/config/routes.rb
CrowdED::Application.routes.draw do
  resources :resources do
  	member do
  		post 'upvote'
  		post 'downvote'
  		end
  	end

  resources :subjects do
  	collection do
  		get 'search'
  	end
  end

  get "home/index"
  

  root :to => 'home#index'

end

crowdED/app/models/resource.rb
class Resource < ActiveRecord::Base
  after_initialize :default_values
  
  attr_accessible :description, :recent_date, :subject_id, :title, :url, :votes
  belongs_to :subject
  validates :url, :presence => true
  validates :title, :presence => true
  validates :subject_id, :presence => true
  default_scope order('created_at ASC')


  def self.search(search)
  	if search
  		find(:all, :conditions => ['title LIKE ? OR description LIKE ?', "%#{search}%", "%#{search}%"])
  	else
  		find(:all)	
  	end
  end
  
  private
    def default_values
      self.votes ||= 0
    end
end

crowdED/app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true
  has_many :resources, :order => 'votes DESC'
  default_scope order('name ASC')

  
  def self.search(search)
  	if search
  		find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  	else
  		find(:all)	
  	end
  end
  
end

crowdED/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

crowdED/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

crowdED/app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  # GET /resources
  # GET /resources.json
  
  def index
    @resources = Resource.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resources }
    end
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
    @resource = Resource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resource }
    end
  end

  # GET /resources/new
  # GET /resources/new.json
  def new
    @resource = Resource.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resource }
    end
  end

  # GET /resources/1/edit
  def edit
    @resource = Resource.find(params[:id])
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(params[:resource])

    respond_to do |format|
      if @resource.save
        format.html { redirect_to resources_path, notice: 'Resource was successfully created.' }
        format.json { render json: @resource, status: :created, location: @resource }
      else
        format.html { render action: "new" }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resources/1
  # PUT /resources/1.json
  def update
    @resource = Resource.find(params[:id])

    respond_to do |format|
      if @resource.update_attributes(params[:resource])
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource = Resource.find(params[:id])
    @resource.destroy

    respond_to do |format|
      format.html { redirect_to resources_url }
      format.json { head :no_content }
    end
  end
  
  def upvote
  	@resource = Resource.find(params[:id])
  	@resource.increment!(:votes, by = 1)
 	  	redirect_to(:back)
  end
  
  def downvote
    @resource = Resource.find(params[:id])
  	@resource.decrement!(:votes, by = 1)
 	  	redirect_to(:back)
  end
  
end

crowdED/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  # GET /subjects
  # GET /subjects.json
  def index
  	@subjects = Subject.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subject = Subject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/new
  # GET /subjects/new.json
  def new
    @subject = Subject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
    @subject = Subject.find(params[:id])
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(params[:subject])

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render json: @subject, status: :created, location: @subject }
      else
        format.html { render action: "new" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subjects/1
  # PUT /subjects/1.json
  def update
    @subject = Subject.find(params[:id])

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :no_content }
    end
  end

end

crowdED/app/helpers/application_helper.rb
module ApplicationHelper
end

crowdED/app/helpers/home_helper.rb
module HomeHelper
end

crowdED/app/helpers/resources_helper.rb
module ResourcesHelper
end

crowdED/app/helpers/subjects_helper.rb
module SubjectsHelper
end

crowdED/app/views/home/index.html.erb
<!--<%=link_to "Subjects", subjects_path %>
<%=link_to "Resources", resources_path %>-->

<div id="search_Home" class="search">
	<%= form_tag resources_path, :method => 'get' do%>
		<%= text_field_tag :search, params[:search], :id => 'inptSearch_Home', :class => 'inptSearch', :placeholder => "Search" %>
		<%= submit_tag "Search", :name => nil, :class => 'searchsubmit' %>
	<% end %>
</div>
<div id="pagetitle_Home" class="pagetitle">
	<span class="pagetext">Fresh Lists</span>
</div>
<div id="contentlist_Home" class="contentlist">
	<ul>
		<% @resources = Resource.order("created_at") %>
		<% @resources.each do |r| %>
			<% @subject = Subject.find(r.subject_id) %>
			<li>
			<%= image_tag("http://img.bitpixels.com/getthumbnail?code=12977&url=" + r.url, :class => "resourceimg")%>	
			<span class="resourcetitle"><%= link_to r.title, r.url %></span><br />
			<span class="resourcetags"><%= r.description %></span><br />
			<span class="resourcesubject"><%= @subject.name %></span><br />
			<span class="resourcerank"><%= r.votes %></span>
			<span class="arrowCont">
				<%= link_to image_tag("/assets/upArrow.png", :class => "upArrow"), {:controller => "resources", :action => "upvote", :id => r.id}, :method => :post %>
				<%= link_to image_tag("/assets/downArrow.png", :class => "downArrow"), {:controller => "resources", :action => "downvote", :id => r.id}, :method => :post %>
			</span> 
			</li>
		<% end %>
	</ul>
</div>

crowdED/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrowdED</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
</head>
<body id="home">
	<div id="content_Home" class="content">
		<div class="header">
			<span id="headerText"><b>crowdED</b>: Crowdsourced Educational Lists</span>
		</div>
		<nav id="navCont">
			<ul>
				<li><%= link_to "Discover", subjects_path %></li>
				<li><%= link_to "Home", :controller => "home", :action => "index" %></li>
				<li><%= link_to "Share", new_resource_path %></li>
			</ul>
		</nav>
		<%= yield %>
	</div>
</body>
</html>

crowdED/app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :subject_id %><br />
    <%= collection_select(:resource, :subject_id, Subject.all, :id, :name)%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

crowdED/app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

crowdED/app/views/resources/index.html.erb
<!--<%=link_to "Subjects", subjects_path %>
<%=link_to "Resources", resources_path %>-->

<div id="search_Home" class="search">
	<%= form_tag 'home/index', :method => 'get' do%>
		<%= text_field_tag :search, params[:search], :id => 'inptSearch_Home', :class => 'inptSearch' %>
		<%= submit_tag "Search", :name => nil %>
	<% end %>
</div>
<div id="pagetitle_Home" class="pagetitle">
	<span class="pagetext">Fresh Lists</span>
</div>
<div id="contentlist_Home" class="contentlist">
	<ul>
		<% @resources.each do |r| %>
			<% @subject = Subject.find(r.subject_id) %>
			<li>
			<%= image_tag("http://img.bitpixels.com/getthumbnail?code=12977&url=" + r.url, :class => "resourceimg")%>	
			<span class="resourcetitle"><%= link_to r.title, r.url %></span><br />
			<span class="resourcetags"><%= r.description %></span><br />
			<span class="resourcesubject"><%= @subject.name %></span><br />
			<span class="resourcerank"><%= r.votes %></span>
			<span class="arrowCont">
				<%= link_to image_tag("/assets/upArrow.png", :class => "upArrow"), {:controller => "resources", :action => "upvote", :id => r.id}, :method => :post %>
				<%= link_to image_tag("/assets/downArrow.png", :class => "downArrow"), {:controller => "resources", :action => "downvote", :id => r.id}, :method => :post %>
			</span> 
			</li>
		<% end %>
	</ul>
</div>

crowdED/app/views/resources/new.html.erb
<%= render 'form' %>

<!--<%= link_to 'Back', resources_path, :class => "back" %>-->

crowdED/app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @resource.title %>
</p>

<p>
  <b>Url:</b>
  <%= @resource.url %>
</p>

<p>
  <b>Description:</b>
  <%= @resource.description %>
</p>

<p>
  <b>recent_date:</b>
  <%= @resource.recent_date %>
</p>

<p>
  <b>Subject:</b>
  <%= @resource.subject_id %>
</p>

<p>
  <b>Votes:</b>
  <%= @resource.votes %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

crowdED/app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

crowdED/app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

crowdED/app/views/subjects/index.html.erb
<div id="search_Home" class="search">	
	<%= form_tag subjects_path, :method => 'get' do%>
		<%= text_field_tag :search, params[:search], :id => 'inptSearch_Home', :class => 'inptSearch', :placeholder => "Search" %>
		<%= submit_tag "Search", :name => nil, :class => 'searchsubmit' %>
	<% end %>
</div>
<div id="pagetitle_Home" class="pagetitle">
	<span class="pagetext">Browse Subjects</span>
</div>
<div id="contentlist_Subject" class="contentlist">
	<ul>
	
	<% @subjects.each do |subject| %>
    	<li>
    	<span class="subjecttitle"><%= link_to subject.name, subject %></span>
    	<span class="subjectlinks"><%= subject.resources.size %> Resources </span>
    	</li>
    <% end %>
    </ul>
</div>

crowdED/app/views/subjects/new.html.erb
<h1>New subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

crowdED/app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<div id="pagetitle_Home" class="pagetitle">
	<span class="pagetext"><%= @subject.name %></span>
</div>



<div id="contentlist_Home" class="contentlist">
	<ul>
	<% @resources = @subject.resources %>
	<% @resources.each do |r| %>
			<% @subject = Subject.find(r.subject_id) %>
			<li>
			<%= image_tag("http://img.bitpixels.com/getthumbnail?code=12977&url=" + r.url, :class => "resourceimg")%>	
			<span class="resourcetitle"><%= link_to r.title, r.url %></span><br />
			<span class="resourcetags"><%= r.description %></span><br />
			<span class="resourcesubject"><%= @subject.name %></span><br />
			<span class="resourcerank"><%= r.votes %></span>
			<span class="arrowCont">
				<%= link_to image_tag("/assets/upArrow.png", :class => "upArrow"), {:controller => "resources", :action => "upvote", :id => r.id}, :method => :post %>
				<%= link_to image_tag("/assets/downArrow.png", :class => "downArrow"), {:controller => "resources", :action => "downvote", :id => r.id}, :method => :post %>
			</span> 
			</li>
		<% end %>
	</ul>
</div>